#include <algorithm>
#include <chrono>
#include <complex>
#include <ctime>
#include <iomanip>
#include <iostream>
#include <string>
#include <vector>

#include "BasisSet.h"
#include "C4_DHF.h"
#include "DiracKinetic.h"
#include "GitVersion.h"  // generated by the Makefile; defines RERDMFT_GIT_SHA
#include "Input.h"
#include "Integrals.h"
#include "KramersSymmetry.h"
#include "LinearAlgebra.h"
#include "MolecularBasis.h"
#include "NuclearAttraction.h"
#include "RkbDensityMatrix.h"
#include "RkbFockMatrix.h"
#include "RkbHamiltonian.h"
#include "RkbOrthogonalization.h"
#include "RkbOverlap.h"
#include "RkbPositiveEnergyHamiltonian.h"
#include "RkbTransformation.h"
#include "RkbTwoElectron.h"
#include "SchrodingerKinetic.h"
#include "Shell.h"
#include "SmallComponentBasis.h"
#include "SpinorBasis.h"
#include "UkbHamiltonian.h"
#include "Vext.h"

namespace {

// Prints a wall-clock timestamp plus the elapsed time since `since` (the
// previous checkpoint) and since `start` (program start), then updates
// `since` to now -- so a sequence of calls gives a running per-phase
// breakdown (e.g. "how long did just the two-electron integrals take")
// without needing to store each duration separately at the call site.
void logTiming(const std::string& label, std::chrono::steady_clock::time_point start,
                std::chrono::steady_clock::time_point& since) {
  const auto now_steady = std::chrono::steady_clock::now();
  const auto now_wall = std::chrono::system_clock::now();
  const std::time_t now_time_t = std::chrono::system_clock::to_time_t(now_wall);
  const double since_previous =
      std::chrono::duration<double>(now_steady - since).count();
  const double since_start = std::chrono::duration<double>(now_steady - start).count();
  std::cout << label << ": " << std::put_time(std::localtime(&now_time_t), "%Y-%m-%d %H:%M:%S")
             << "  (+" << std::fixed << std::setprecision(3) << since_previous
             << " s this phase, " << since_start << " s total)\n";
  std::cout << std::setprecision(6);
  since = now_steady;
}

void printAoList(const std::string& label,
                  const std::vector<rerdmft::BasisFunction>& functions,
                  const std::vector<rerdmft::NormalizationCheck>& normalization) {
  std::cout << "\n" << label << " (" << functions.size()
             << " total), normalized via libcint overlap integrals:\n";
  for (std::size_t i = 0; i < functions.size(); ++i) {
    const auto& fn = functions[i];
    const auto& check = normalization[i];
    std::cout << "  " << std::setw(2) << fn.element << "  "
               << rerdmft::angularMomentumLabel(fn.l) << "(" << fn.cartesian.lx
               << fn.cartesian.ly << fn.cartesian.lz << ")  "
               << "center=(" << fn.x << ", " << fn.y << ", " << fn.z << ")  "
               << "nprim=" << fn.exponents.size() << "  "
               << "S_self(before)=" << check.self_overlap_before << "  "
               << (check.was_renormalized ? "renormalized" : "already normalized")
               << "\n";
  }
}

struct BlockNorms {
  double max_hermiticity_error = 0.0;
  double max_large_large = 0.0;
  double max_large_small = 0.0;
  double max_small_small = 0.0;
};

BlockNorms analyzeBlocks(const rerdmft::Matrix<std::complex<double>>& m,
                          std::size_t n_large_total) {
  BlockNorms norms;
  for (std::size_t p = 0; p < m.rows(); ++p) {
    for (std::size_t q = 0; q < m.cols(); ++q) {
      norms.max_hermiticity_error =
          std::max(norms.max_hermiticity_error, std::abs(m(p, q) - std::conj(m(q, p))));
      const bool p_large = p < n_large_total;
      const bool q_large = q < n_large_total;
      const double v = std::abs(m(p, q));
      if (p_large && q_large) {
        norms.max_large_large = std::max(norms.max_large_large, v);
      } else if (!p_large && !q_large) {
        norms.max_small_small = std::max(norms.max_small_small, v);
      } else {
        norms.max_large_small = std::max(norms.max_large_small, v);
      }
    }
  }
  return norms;
}

void printMatrixDiagnostics(const std::string& label,
                             const rerdmft::Matrix<std::complex<double>>& m,
                             std::size_t n_large_total) {
  const BlockNorms norms = analyzeBlocks(m, n_large_total);
  std::cout << "\n" << label << ":\n";
  std::cout << "  Dimensions: " << m.rows() << " x " << m.cols() << "\n";
  std::cout << "  Max |M - M^dagger| (Hermiticity check): " << norms.max_hermiticity_error << "\n";
  std::cout << "  Max |M| within Large-Large block: " << norms.max_large_large << "\n";
  std::cout << "  Max |M| within Large-Small block: " << norms.max_large_small << "\n";
  std::cout << "  Max |M| within Small-Small block: " << norms.max_small_small << "\n";
}

void printWelcomeBanner() {
  constexpr int kWidth = 70;
  auto center = [](const std::string& text) {
    const int pad = kWidth - static_cast<int>(text.size());
    const int left = pad > 0 ? pad / 2 : 0;
    const int right = pad > 0 ? pad - left : 0;
    return std::string(static_cast<std::size_t>(left), ' ') + text +
           std::string(static_cast<std::size_t>(right), ' ');
  };
  const std::string border = "+" + std::string(kWidth, '-') + "+";
  const std::string blank = "|" + std::string(kWidth, ' ') + "|";

  std::cout << border << "\n";
  std::cout << blank << "\n";
  std::cout << "|" << center("R e R D M F T") << "|\n";
  std::cout << blank << "\n";
  std::cout << "|" << center("Relativistic Reduced Density Matrix Functional Theory") << "|\n";
  std::cout << "|" << center("-- developed with Claude --") << "|\n";
  std::cout << blank << "\n";
  std::cout << "|" << center("M. Rodriguez-Mayorga, PhD.") << "|\n";
  std::cout << "|" << center("marm3.14@gmail.com") << "|\n";
  std::cout << blank << "\n";
  std::cout << border << "\n\n";
}

void printFarewell() {
  static const char* kArt = R"(
                                                                ███
                                                             ██████████
                                                            ██████████████████
                                         ████              ██████      █████████
                                       ████████           ██████          █████      ███
                                        ████████         ██████             ██     ████
                                        ██████████     ███████       ██          ██████
                             ███         ██████████    ██████        ███         ██████
                             ████         █████████   ███████        ████            ██
                          ████████        ████████    ██████        ████████████      █
                         ████████          ███████    ██████        █████████      █████
                        ████████            ██████    ██████         ████████      █████
                        ████████████         ██████   ███████       ████████        ███
                         ██████████████      █████    ██████     ████████
                             █████████       ████     ███      ███████
                               █████        █████      █       ███
                                          ████████     ███
                                        ███████████   █████
                             ████         ████████    █████           ██████
                     ███  ███ ███  ██         ██       ███      ████  ██ ████  █
                      ███        ██████       ████    ████       ████        ████
                        ███████████          ███       ████         ███████              ███
              █                             ████        ████                            ████
            ██████                      ██████████    ████████                          ████
          ██████████              █████████████████  ██████████████████               █████
         ████████████       █████████     ████████    ██████████████████████        ███████
         ████████████     ████████          ████        ████          ███████      ███████
            █████████    ████████      █    ███         ████              ████     ██████
             ████████   ████████    █████████████     ██████████████       █████    ████
                ████    ██████    ███        ███████████████    ██████       █        █
                 ███        █     ██          ████████████         █████
                     ███         ███            ████████            █████
                     █████      ███████                             ██████       ██
                       ██████ █████   █████                   █████████████  █████
                         ███████         █████             ████        █████████
                           ████            █████       ██████           ██████
                           ███               ██████████████              ████
                           ██                    █████                    █

                                   ███           █    ██        ██
                                    █████████   ███   ███   █████
                                    ███████ ██████████████████ ██
                                     ██      ██           ██   ██
                                      ███    ██           █   ███
                                         ███ ██         ███████
                                           █████      ██████
                                            ██         ██
                                          ██            ██
                                        ███     ███      ███
                                       ████   ███████    ███
                                        ███████████████ ████
                                         ███████ ██ ███████
)";
  std::cout << kArt << "\n";
  std::cout << "\"At last we will reveal ourselves to the Jedi.\n"
                " At last we will have revenge.\"\n\n";
}

}  // namespace

int main(int argc, char** argv) {
  printWelcomeBanner();
  std::cout << "Git commit: " << RERDMFT_GIT_SHA << "\n\n";

  if (argc != 2) {
    std::cerr << "Usage: " << argv[0] << " <input file>\n";
    printFarewell();
    return 1;
  }

  rerdmft::Input input;
  rerdmft::BasisSet basis_set;
  rerdmft::MolecularBasis large_basis;
  rerdmft::SmallComponentBasis small_basis;
  rerdmft::SpinorBasis spinor_basis;
  std::vector<rerdmft::NormalizationCheck> large_normalization;
  std::vector<rerdmft::NormalizationCheck> small_normalization;
  rerdmft::Matrix<std::complex<double>> dirac_kinetic;
  rerdmft::Matrix<std::complex<double>> dirac_rest_energy;
  rerdmft::Matrix<std::complex<double>> vext;
  rerdmft::Matrix<std::complex<double>> h_ukb;
  rerdmft::Matrix<std::complex<double>> rkb_coefficients;
  rerdmft::Matrix<std::complex<double>> h_rkb;
  rerdmft::Matrix<double> s_large;
  rerdmft::Matrix<double> x_large;
  rerdmft::Matrix<double> s_small_ukb;
  rerdmft::Matrix<std::complex<double>> s_small;
  rerdmft::Matrix<std::complex<double>> x_small;
  rerdmft::Matrix<std::complex<double>> x_full;
  rerdmft::Matrix<std::complex<double>> h_rkb_ortho;
  rerdmft::HermitianEigenResult h_rkb_ortho_eig;
  double max_kramers_partner_deviation = 0.0;
  rerdmft::Matrix<std::complex<double>> f_small;
  rerdmft::Matrix<std::complex<double>> h_positive_energy;
  rerdmft::Matrix<std::complex<double>> h_positive_energy_ortho;
  rerdmft::HermitianEigenResult h_positive_energy_eig;
  rerdmft::Matrix<double> h_core_nonrel_ortho;
  rerdmft::SymmetricEigenResult h_core_nonrel_eig;
  rerdmft::Matrix<std::complex<double>> c_dhf;
  rerdmft::Matrix<std::complex<double>> density_matrix;
  rerdmft::RkbTwoElectronTensor c4_spinor_eri;
  rerdmft::Matrix<std::complex<double>> fock_matrix;
  rerdmft::DiracHartreeFockResult dhf_result;
  const auto t_start = std::chrono::steady_clock::now();
  auto t_checkpoint = t_start;
  try {
    input.read(argv[1]);
    basis_set.read(input.basis_file());

    large_basis.build(input.geometry(), basis_set);
    large_normalization = rerdmft::normalizeCartesianBasis(large_basis.functions());

    small_basis.build(input.geometry(), basis_set);
    small_normalization = rerdmft::normalizeCartesianBasis(small_basis.functions());

    spinor_basis.build(large_basis.functions(), small_basis.functions());

    dirac_kinetic = rerdmft::diracKineticMatrix(large_basis.functions(), small_basis.functions(),
                                                 input.speed_of_light());
    dirac_rest_energy = rerdmft::diracRestEnergyMatrix(
        large_basis.functions(), small_basis.functions(), input.speed_of_light());
    vext = rerdmft::vextMatrix(large_basis.functions(), small_basis.functions(),
                                input.geometry());
    h_ukb = rerdmft::ukbHamiltonianMatrix(large_basis.functions(), small_basis.functions(),
                                           input.geometry(), input.speed_of_light());
    rkb_coefficients =
        rerdmft::rkbCoefficients(large_basis.functions(), small_basis.functions());
    h_rkb = rerdmft::rkbHamiltonianMatrix(h_ukb, rkb_coefficients);
    logTiming("H_RKB built", t_start, t_checkpoint);

    s_large = rerdmft::overlapMatrix(large_basis.functions());
    x_large = rerdmft::inverseSqrt(s_large);

    s_small_ukb = rerdmft::overlapMatrix(small_basis.functions());
    s_small = rerdmft::rkbSmallOverlapMatrix(small_basis.functions(), rkb_coefficients);
    x_small = rerdmft::inverseSqrtHermitian(s_small);

    x_full = rerdmft::xFullMatrix(x_large, x_small);
    h_rkb_ortho = rerdmft::hRkbOrthoMatrix(h_rkb, x_full);

    h_rkb_ortho_eig = rerdmft::diagonalizeHermitian(h_rkb_ortho);

    max_kramers_partner_deviation = rerdmft::maxKramersPartnerDeviation(
        h_rkb_ortho_eig.eigenvectors, rkb_coefficients, x_full, s_large, s_small_ukb);

    c_dhf = rerdmft::rkbCoefficientMatrix(x_full, h_rkb_ortho_eig.eigenvectors);
    density_matrix = rerdmft::rkbDensityMatrix(c_dhf, input.n_electrons());

    f_small = rerdmft::rkbSmallVextMatrix(small_basis.functions(), rkb_coefficients,
                                           input.geometry());
    h_positive_energy = rerdmft::rkbPositiveEnergyHamiltonian(h_rkb, s_small, f_small,
                                                               input.speed_of_light());
    h_positive_energy_ortho =
        rerdmft::positiveEnergyOrthoHamiltonian(h_positive_energy, x_large);
    h_positive_energy_eig = rerdmft::diagonalizeHermitian(h_positive_energy_ortho);

    if (input.non_relativistic()) {
      const auto schrodinger_kinetic = rerdmft::schrodingerKineticMatrix(large_basis.functions());
      const auto vext_large =
          rerdmft::nuclearAttractionMatrix(large_basis.functions(), input.geometry());
      const auto h_core_nonrel = schrodinger_kinetic + vext_large;
      h_core_nonrel_ortho = x_large * (h_core_nonrel * x_large);
      h_core_nonrel_eig = rerdmft::diagonalizeSymmetric(h_core_nonrel_ortho);
    }

    if (input.c4_spinor()) {
      c4_spinor_eri = rerdmft::rkbTwoElectronIntegrals(large_basis.functions(),
                                                            small_basis.functions(),
                                                            rkb_coefficients);
      logTiming("Two-electron integrals built", t_start, t_checkpoint);

      fock_matrix = rerdmft::rkbFockMatrix(h_rkb, c4_spinor_eri, density_matrix);

      dhf_result = rerdmft::runDiracHartreeFockScf(
          h_rkb, c4_spinor_eri, x_full, density_matrix, input.n_electrons(), input.geometry(),
          input.mixing(), input.max_iterations(), input.energy_tolerance(),
          input.density_tolerance());
      logTiming("SCF loop complete", t_start, t_checkpoint);
    }
  } catch (const std::exception& e) {
    std::cerr << "Error: " << e.what() << "\n";
    printFarewell();
    return 1;
  }

  std::cout << "Number of electrons: " << input.n_electrons() << "\n";
  std::cout << "Basis set file:      " << input.basis_file() << "\n";
  std::cout << "Speed of light (c):  " << input.speed_of_light() << " a.u.\n";
  std::cout << "Geometry (" << input.geometry().size() << " atoms):\n";
  std::cout << std::fixed << std::setprecision(6);
  for (const auto& atom : input.geometry()) {
    std::cout << "  " << std::setw(2) << atom.symbol << "  " << std::setw(12)
               << atom.x << "  " << std::setw(12) << atom.y << "  "
               << std::setw(12) << atom.z << "\n";
  }

  const std::size_t n_large = spinor_basis.nLarge();
  const std::size_t n_small = spinor_basis.nSmall();

  if (input.debug()) {
    printAoList("Large-component cartesian atomic orbitals", large_basis.functions(),
                large_normalization);
    printAoList("Small-component cartesian atomic orbitals (unrestricted kinetic balance)",
                small_basis.functions(), small_normalization);

    std::cout << "\nFour-component spinor basis:\n";
    std::cout << "  Large-component AOs per spin block: " << spinor_basis.nLarge() << "\n";
    std::cout << "  Small-component AOs per spin block: " << spinor_basis.nSmall() << "\n";
    std::cout << "  Total spinor basis functions: " << spinor_basis.size()
               << " (Large-alpha, Large-beta, Small-alpha, Small-beta)\n";
    const auto describeSpinor = [&](std::size_t index) {
      const auto& ao = spinor_basis.ao(index);
      std::cout << "    index " << index << "  "
                 << rerdmft::spinBlockLabel(spinor_basis.block(index)) << "  ao="
                 << spinor_basis.aoIndex(index) << "  " << ao.element << "  "
                 << rerdmft::angularMomentumLabel(ao.l) << "(" << ao.cartesian.lx
                 << ao.cartesian.ly << ao.cartesian.lz << ")\n";
    };
    if (n_large > 0) {
      describeSpinor(0);
      describeSpinor(n_large - 1);
      describeSpinor(n_large);
      describeSpinor(2 * n_large - 1);
    }
    if (n_small > 0) {
      describeSpinor(2 * n_large);
      describeSpinor(2 * n_large + n_small - 1);
      describeSpinor(2 * n_large + n_small);
      describeSpinor(spinor_basis.size() - 1);
    }

    printMatrixDiagnostics("Dirac kinetic energy matrix T = -i c (alpha . grad_r)", dirac_kinetic,
                            2 * n_large);
    if (n_large > 0 && n_small > 0) {
      // Large-alpha[0] paired with Small-beta[0], i.e. the alpha-beta spin
      // block -c*i*(Dx - i*Dy): typically nonzero and illustrates that the
      // matrix is genuinely complex (from the sigma_y contribution), unlike
      // e.g. the alpha-alpha block for an S/p_z pair on the same center,
      // which vanishes exactly by parity.
      const std::size_t col = 2 * n_large + n_small;
      const auto& sample = dirac_kinetic(0, col);
      std::cout << "  T[0, " << col << "] (Large-alpha[0], Small-beta[0]) = " << sample.real()
                 << (sample.imag() >= 0 ? " + " : " - ") << std::abs(sample.imag()) << "i\n";
    }

    printMatrixDiagnostics(
        "Dirac rest-energy alignment matrix diag(0_2, -2c^2 I_2) (metric-weighted)",
        dirac_rest_energy, 2 * n_large);
    if (n_large > 0) {
      std::cout << "  M[0,0] (Large-alpha[0] self, expect 0): " << dirac_rest_energy(0, 0).real()
                 << "\n";
    }
    if (n_small > 0) {
      const std::size_t idx = 2 * n_large;
      std::cout << "  M[" << idx << "," << idx << "] (Small-alpha[0] self, expect -2c^2 = "
                 << -2.0 * input.speed_of_light() * input.speed_of_light()
                 << "): " << dirac_rest_energy(idx, idx).real() << "\n";
    }

    const auto dirac_core = dirac_kinetic + dirac_rest_energy;
    printMatrixDiagnostics("Dirac core matrix T_D = kinetic + rest-energy alignment", dirac_core,
                            2 * n_large);

    printMatrixDiagnostics("Vext matrix: spinor_a^dagger Vext(r) I_4x4 spinor_b", vext,
                            2 * n_large);
    if (n_large > 0) {
      std::cout << "  Vext[0,0] (Large-alpha[0] self, expect large and negative): "
                 << vext(0, 0).real() << "\n";
    }
    if (n_small > 0) {
      const std::size_t idx = 2 * n_large;
      std::cout << "  Vext[" << idx << "," << idx
                 << "] (Small-alpha[0] self, expect large and negative): "
                 << vext(idx, idx).real() << "\n";
    }

    printMatrixDiagnostics(
        "Unrestricted kinetic balance Hamiltonian H_UKB = T_kinetic + rest-energy alignment + Vext",
        h_ukb, 2 * n_large);

    std::cout << "\nRKB transformation coefficients C (sigma.p |Large_p> = sum_q C_pq |Small_q>):\n";
    std::cout << "  Dimensions: " << rkb_coefficients.rows() << " x " << rkb_coefficients.cols()
               << " (rows: Large-alpha/beta spin-orbitals; cols: Small-alpha/beta spin-orbitals)\n";

    printMatrixDiagnostics(
        "Restricted kinetic balance Hamiltonian H_RKB = W^dagger H_UKB W, W=[[I,0],[0,C^T]]",
        h_rkb, rkb_coefficients.rows());
    // W's top rows are just the identity on the Large block, so H_RKB's
    // Large-Large block must be byte-for-byte the same as H_UKB's.
    double max_large_block_change = 0.0;
    for (std::size_t p = 0; p < 2 * n_large; ++p) {
      for (std::size_t q = 0; q < 2 * n_large; ++q) {
        max_large_block_change = std::max(max_large_block_change, std::abs(h_rkb(p, q) - h_ukb(p, q)));
      }
    }
    std::cout << "  Max |H_RKB - H_UKB| within Large-Large block (expect exactly 0): "
               << max_large_block_change << "\n";

    std::cout << "\nLoewdin orthonormalization matrix X_Large = S_Large^-1/2:\n";
    std::cout << "  Dimensions: " << x_large.rows() << " x " << x_large.cols() << "\n";
    const auto s_large_check = rerdmft::overlapMatrix(large_basis.functions());
    double max_asymmetry = 0.0;
    double max_lowdin_error = 0.0;
    const auto xsx = x_large * (s_large_check * x_large);
    for (std::size_t i = 0; i < x_large.rows(); ++i) {
      for (std::size_t j = 0; j < x_large.cols(); ++j) {
        max_asymmetry = std::max(max_asymmetry, std::abs(x_large(i, j) - x_large(j, i)));
        const double expected = (i == j) ? 1.0 : 0.0;
        max_lowdin_error = std::max(max_lowdin_error, std::abs(xsx(i, j) - expected));
      }
    }
    std::cout << "  Max |X_Large - X_Large^T| (symmetry check): " << max_asymmetry << "\n";
    std::cout << "  Max |X_Large S_Large X_Large - I| (Loewdin identity check): "
               << max_lowdin_error << "\n";

    std::cout << "\nRKB Small-component overlap S_small = C^dagger S_uKB C:\n";
    std::cout << "  Dimensions: " << s_small.rows() << " x " << s_small.cols() << "\n";
    double max_s_herm_err = 0.0;
    for (std::size_t i = 0; i < s_small.rows(); ++i) {
      for (std::size_t j = 0; j < s_small.cols(); ++j) {
        max_s_herm_err = std::max(max_s_herm_err, std::abs(s_small(i, j) - std::conj(s_small(j, i))));
      }
    }
    std::cout << "  Max |S_small - S_small^dagger| (Hermiticity check): " << max_s_herm_err << "\n";

    std::cout << "\nLoewdin orthonormalization matrix X_small = S_small^-1/2:\n";
    std::cout << "  Dimensions: " << x_small.rows() << " x " << x_small.cols() << "\n";
    const auto xsx_small = x_small * (s_small * x_small);
    double max_x_small_herm_err = 0.0;
    double max_small_lowdin_error = 0.0;
    for (std::size_t i = 0; i < x_small.rows(); ++i) {
      for (std::size_t j = 0; j < x_small.cols(); ++j) {
        max_x_small_herm_err =
            std::max(max_x_small_herm_err, std::abs(x_small(i, j) - std::conj(x_small(j, i))));
        const double expected = (i == j) ? 1.0 : 0.0;
        max_small_lowdin_error = std::max(max_small_lowdin_error, std::abs(xsx_small(i, j) - expected));
      }
    }
    std::cout << "  Max |X_small - X_small^dagger| (Hermiticity check): " << max_x_small_herm_err
               << "\n";
    std::cout << "  Max |X_small S_small X_small - I| (Loewdin identity check): "
               << max_small_lowdin_error << "\n";

    std::cout << "\nX_full = diag(X_Large, X_Large, X_small):\n";
    std::cout << "  Dimensions: " << x_full.rows() << " x " << x_full.cols() << "\n";

    printMatrixDiagnostics("Orthonormalized RKB Hamiltonian H_RKB_ortho = X_full^dagger H_RKB X_full",
                            h_rkb_ortho, rkb_coefficients.rows());
  }

  std::cout << "\nH_UKB dimensions: " << h_ukb.rows() << " x " << h_ukb.cols() << "\n";
  std::cout << "RKB coefficients C dimensions: " << rkb_coefficients.rows() << " x "
             << rkb_coefficients.cols() << "\n";
  std::cout << "H_RKB dimensions: " << h_rkb.rows() << " x " << h_rkb.cols() << "\n";
  std::cout << "X_Large dimensions: " << x_large.rows() << " x " << x_large.cols() << "\n";
  std::cout << "S_small dimensions: " << s_small.rows() << " x " << s_small.cols() << "\n";
  std::cout << "X_small dimensions: " << x_small.rows() << " x " << x_small.cols() << "\n";
  std::cout << "X_full dimensions: " << x_full.rows() << " x " << x_full.cols() << "\n";
  std::cout << "H_RKB_ortho dimensions: " << h_rkb_ortho.rows() << " x " << h_rkb_ortho.cols()
             << "\n";

  std::cout << "\nEigenvalues of H_RKB_ortho (Kramers pairs, even/odd indices side by side):\n";
  std::cout << "  " << std::setw(6) << "index" << std::setw(20) << "E (even)" << std::setw(10)
             << "index" << std::setw(20) << "E (odd)" << "\n";
  const auto& eigenvalues = h_rkb_ortho_eig.eigenvalues;
  double max_kramers_splitting = 0.0;
  for (std::size_t i = 0; i + 1 < eigenvalues.size(); i += 2) {
    std::cout << "  " << std::setw(6) << i << std::setw(20) << eigenvalues[i] << std::setw(10)
               << (i + 1) << std::setw(20) << eigenvalues[i + 1] << "\n";
    max_kramers_splitting = std::max(max_kramers_splitting, std::abs(eigenvalues[i] - eigenvalues[i + 1]));
  }
  std::cout << "Max |E(even) - E(odd)| Kramers-pair splitting (expect ~0): " << max_kramers_splitting
             << "\n";
  std::cout << "Max Kramers eigenvector-partner deviation, 1-|<odd|Theta even>_S| (expect ~0): "
             << max_kramers_partner_deviation << "\n";

  {
    const std::size_t n_rkb = h_rkb_ortho.rows();
    const std::size_t occ_start = n_rkb / 2;
    const std::size_t occ_end = occ_start + static_cast<std::size_t>(input.n_electrons());
    std::cout << "\nC_DHF = X_full * U dimensions: " << c_dhf.rows() << " x " << c_dhf.cols()
               << "\n";
    std::cout << "Density matrix P dimensions: " << density_matrix.rows() << " x "
               << density_matrix.cols() << "\n";
    std::cout << "Occupied (lowest positive-energy) spinor indices: [" << occ_start << ", "
               << occ_end << ")\n";
    if (input.debug()) {
      const auto s_full = rerdmft::sFullMatrix(s_large, s_small);
      std::complex<double> trace_ps(0.0, 0.0);
      for (std::size_t i = 0; i < n_rkb; ++i) {
        for (std::size_t j = 0; j < n_rkb; ++j) {
          trace_ps += density_matrix(i, j) * s_full(j, i);
        }
      }
      std::cout << "  Max |P - P^dagger| (Hermiticity check): " << [&] {
        double max_err = 0.0;
        for (std::size_t i = 0; i < n_rkb; ++i)
          for (std::size_t j = 0; j < n_rkb; ++j)
            max_err = std::max(max_err, std::abs(density_matrix(i, j) -
                                                  std::conj(density_matrix(j, i))));
        return max_err;
      }() << "\n";
      std::cout << "  Tr(P S_full), expect exactly NELEC = " << input.n_electrons() << ": "
                 << trace_ps.real() << (trace_ps.imag() >= 0 ? " + " : " - ")
                 << std::abs(trace_ps.imag()) << "i\n";
    }
  }

  if (input.debug()) {
    std::cout << "\nPositive-energy eigenvalues (exact Feshbach reduction of H_RKB's Small-Small\n"
                  "block -- unlike H_RKB_ortho above, this never sums a -2c^2 term against an\n"
                  "O(1) one in floating point, so it stays accurate and exactly Kramers-paired\n"
                  "at any SPEED_OF_LIGHT, including the c -> infinity nonrelativistic limit):\n";
    std::cout << "  " << std::setw(6) << "index" << std::setw(20) << "E (even)" << std::setw(10)
               << "index" << std::setw(20) << "E (odd)" << "\n";
    const auto& positive_energy_eigenvalues = h_positive_energy_eig.eigenvalues;
    double max_positive_energy_kramers_splitting = 0.0;
    for (std::size_t i = 0; i + 1 < positive_energy_eigenvalues.size(); i += 2) {
      std::cout << "  " << std::setw(6) << i << std::setw(20) << positive_energy_eigenvalues[i]
                 << std::setw(10) << (i + 1) << std::setw(20) << positive_energy_eigenvalues[i + 1]
                 << "\n";
      max_positive_energy_kramers_splitting = std::max(
          max_positive_energy_kramers_splitting,
          std::abs(positive_energy_eigenvalues[i] - positive_energy_eigenvalues[i + 1]));
    }
    std::cout << "Max |E(even) - E(odd)| Kramers-pair splitting, positive-energy branch (expect ~0): "
               << max_positive_energy_kramers_splitting << "\n";
  }

  if (input.non_relativistic()) {
    std::cout << "\nNonrelativistic (Schrodinger) core Hamiltonian eigenvalues:\n";
    for (std::size_t i = 0; i < h_core_nonrel_eig.eigenvalues.size(); ++i) {
      std::cout << "  " << std::setw(6) << i << std::setw(20) << h_core_nonrel_eig.eigenvalues[i]
                 << "\n";
    }
  }

  if (input.c4_spinor()) {
    const std::size_t n_spinor = c4_spinor_eri.dim();
    std::cout << "\nTwo-electron Coulomb repulsion tensor <Spinor_A Spinor_B|Spinor_C Spinor_D>,\n"
                 "restricted kinetic balance basis (physics notation; A,C on electron 1, B,D on\n"
                 "electron 2):\n";
    std::cout << "  Dimensions: " << n_spinor << " x " << n_spinor << " x " << n_spinor << " x "
               << n_spinor << "\n";
    std::cout << "  Stored values (electron-exchange-unique half): " << c4_spinor_eri.storedCount()
               << " (dense would be " << n_spinor * n_spinor * n_spinor * n_spinor << ")\n";
    if (input.debug()) {
      double max_exchange_err = 0.0;
      double max_herm_err = 0.0;
      for (std::size_t a = 0; a < n_spinor; ++a) {
        for (std::size_t b = 0; b < n_spinor; ++b) {
          for (std::size_t c = 0; c < n_spinor; ++c) {
            for (std::size_t d = 0; d < n_spinor; ++d) {
              const auto v_abcd = c4_spinor_eri(a, b, c, d);
              max_exchange_err =
                  std::max(max_exchange_err, std::abs(v_abcd - c4_spinor_eri(b, a, d, c)));
              max_herm_err = std::max(
                  max_herm_err, std::abs(v_abcd - std::conj(c4_spinor_eri(c, d, a, b))));
            }
          }
        }
      }
      std::cout << "  Max |<AB|CD> - <BA|DC>| (electron-exchange symmetry, expect ~0): "
                 << max_exchange_err << "\n";
      std::cout << "  Max |<AB|CD> - conj(<CD|AB>)| (Hermiticity, expect ~0): " << max_herm_err
                 << "\n";
    }

    std::cout << "\nFock matrix F = H_RKB + J - K_same - K_opposite (RKB spinor AO basis):\n";
    std::cout << "  Dimensions: " << fock_matrix.rows() << " x " << fock_matrix.cols() << "\n";
    if (input.debug()) {
      double max_herm_err = 0.0;
      for (std::size_t p = 0; p < fock_matrix.rows(); ++p) {
        for (std::size_t r = 0; r < fock_matrix.cols(); ++r) {
          max_herm_err =
              std::max(max_herm_err, std::abs(fock_matrix(p, r) - std::conj(fock_matrix(r, p))));
        }
      }
      std::cout << "  Max |F - F^dagger| (Hermiticity check): " << max_herm_err << "\n";
    }

    std::cout << "\n4-component Dirac-Hartree-Fock SCF (linear density mixing = "
               << input.mixing() << "):\n";
    for (const auto& it : dhf_result.history) {
      std::cout << "  Iteration " << std::setw(3) << it.iteration << "  E = " << std::setw(16)
                 << std::setprecision(10) << it.energy << std::setprecision(6);
      if (it.iteration > 1) {
        std::cout << "  dE = " << it.energy_change << "  dP = " << it.density_change;
      }
      std::cout << "\n";
      if (input.debug()) {
        std::cout << "    One-body (Fock_ortho) state energies (Kramers pairs, even/odd side by "
                     "side):\n";
        const auto& oe = it.orbital_energies;
        for (std::size_t i = 0; i + 1 < oe.size(); i += 2) {
          std::cout << "      " << std::setw(6) << i << std::setw(20) << oe[i] << std::setw(10)
                     << (i + 1) << std::setw(20) << oe[i + 1] << "\n";
        }
      }
    }
    std::cout << "  " << (dhf_result.converged ? "Converged" : "Did NOT converge") << " after "
               << dhf_result.iterations << " iteration(s)\n";
    std::cout << "  Electronic energy:          " << std::setprecision(10)
               << dhf_result.electronic_energy << " Hartree\n";
    std::cout << "  Nuclear repulsion energy:   " << dhf_result.nuclear_repulsion_energy
               << " Hartree\n";
    std::cout << "  Total DHF (4C) energy:      " << dhf_result.total_energy << " Hartree\n";
    std::cout << std::setprecision(6);

    double max_fock_kramers_splitting = 0.0;
    const auto& final_oe = dhf_result.orbital_energies;
    for (std::size_t i = 0; i + 1 < final_oe.size(); i += 2) {
      max_fock_kramers_splitting =
          std::max(max_fock_kramers_splitting, std::abs(final_oe[i] - final_oe[i + 1]));
    }
    const double fock_kramers_partner_deviation = rerdmft::maxKramersPartnerDeviation(
        dhf_result.fock_ortho_eigenvectors, rkb_coefficients, x_full, s_large, s_small_ukb);
    std::cout << "  Fock_ortho Max |E(even) - E(odd)| Kramers-pair splitting (expect ~0): "
               << max_fock_kramers_splitting << "\n";
    std::cout << "  Fock_ortho Max Kramers eigenvector-partner deviation, "
                 "1-|<odd|Theta even>_S| (expect ~0): "
               << fock_kramers_partner_deviation << "\n";
  }

  printFarewell();
  return 0;
}
